package demo.mapper;

import com.cxd.baseservice.mapper.BaseMapper;
import demo.entity.CfgSearchRecommend;
import demo.po.CfgSearchRecommendExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * Created by wenter on 2019/1/31.
 */
public interface CfgSearchRecommendMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int countByExample(CfgSearchRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int deleteByExample(CfgSearchRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int insert(CfgSearchRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int insertSelective(CfgSearchRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    List<CfgSearchRecommend> selectByExample(CfgSearchRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    CfgSearchRecommend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CfgSearchRecommend record, @Param("example") CfgSearchRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CfgSearchRecommend record, @Param("example") CfgSearchRecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CfgSearchRecommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cfg_search_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CfgSearchRecommend record);
}
